### ISSUE TITLE
Faster palette switching

### ISSUE THREAD

**Issue by jibbers42** [rdlauer/nativescript-theme-builder#5]
It would be nice if you could browse and modify palettes even faster. I've mocked up an idea to cycle palettes and be able to modify them using the nav header. I won't be able to tackle this, but hopefully someone can take this on - or do something better!

![theme-nav-switcher](https://cloud.githubusercontent.com/assets/797824/26262854/3f3fde56-3ca4-11e7-9ad6-40612c85b901.png)

**Comment by rdlauer** [comment]
This is (finally) done :)
