### ISSUE TITLE
What is this element called?

### ISSUE THREAD

**Issue by pauldbentley** [rdlauer/nativescript-theme-builder#7]
What is this element called and can we change the colour?
![capture](https://user-images.githubusercontent.com/5243982/46731335-534a6780-cc82-11e8-8462-847e11b3b6fb.PNG)

**Comment by rdlauer** [comment]
Those are just individually styled ListView items. I don't believe there is a separate concept of a "separator" item in ListViews on either iOS or Android. You can change the style with `color`, `separator-color`, and `background-color` CSS properties.
