### ISSUE TITLE
Download theme  - Custom Css doesn't match the input

### ISSUE THREAD

**Issue by LeGnours** [rdlauer/nativescript-theme-builder#8]
After creating a new theme using NativeScript Theme builder, if I want to download the theme and load it back using import of the NativeScript Theme builder, themes doesn't match.

After looking into the issue, I've noticed that the custom.css created by Nativescript theme builder is not entirely accurate and a lot of color changes are not properly saved.

How to reproduce:
- Go to https://www.nativescriptthemebuilder.com/#
- Change Action Bar Color to 'Red', View Background Color to Green, Text Color to pink
- Click on the button 'Download Theme'
- Click on the 'Import' button and choose the file you've just downloaded.
- On my side, the View Background color switch back to Blue.

**Comment by rdlauer** [comment]
Thanks for pointing out the issue! This has been resolved (I believe) with the latest commit. Please let me know if you spot any other problems.
